In [14]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [15]:
from matplotlib import font_manager, rc
font_path = "C:/Windows/Fonts/malgun.ttf"
font = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font)

In [64]:
file_path = "./data/KOSIS/채소생산량_딸기(2011~2020).csv"
df = pd.read_csv(file_path, encoding="EUC_KR")
df

,시도별,2011,2011.1,2011.2,2011.3,2011.4,2012,2012.1,2012.2,2012.3,...,2019,2019.1,2019.2,2019.3,2019.4,2020,2020.1,2020.2,2020.3,2020.4
0,시도별,딸기:면적 (ha),생산량 (톤),시설딸기:면적 (ha),10a당 생산량 (kg),생산량 (톤),딸기:면적 (ha),생산량 (톤),시설딸기:면적 (ha),10a당 생산량 (kg),...,딸기:면적 (ha),생산량 (톤),시설딸기:면적 (ha),10a당 생산량 (kg),생산량 (톤),딸기:면적 (ha),생산량 (톤),시설딸기:면적 (ha),10a당 생산량 (kg),생산량 (톤)
1,계,5816,171519,5681,2979,169243,6435,192140,6290,3005,...,6462,234225,6421,3633,233291,5683,163646,5634,2885,162520
2,서울특별시,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,부산광역시,0,0,0,0,0,4,132,4,3299,...,0,5,0,0,0,1,42,1,2759,24
4,대구광역시,0,0,0,0,0,0,0,0,0,...,2,62,2,3403,62,0,0,0,0,0
5,인천광역시,11,254,0,0,0,9,105,0,0,...,24,601,19,2602,504,26,659,24,2601,617
6,광주광역시,47,1213,46,2583,1188,46,1256,46,2731,...,72,2662,72,3679,2660,64,2180,64,3392,2180
7,대전광역시,0,0,0,0,0,0,0,0,0,...,0,5,0,1404,2,0,0,0,0,0
8,울산광역시,0,0,0,0,0,0,0,0,0,...,18,410,17,2238,381,22,471,20,2074,415
9,세종특별자치시,-,-,-,-,-,-,-,-,-,...,20,463,20,2348,463,6,146,6,2439,146
10,경기도,109,2886,108,2651,2863,99,2141,99,2163,...,114,3017,109,2675,2905,122,3219,115,2669,3077
11,강원도,54,1151,54,2131,1151,42,918,42,2185,...,65,1382,54,2179,1171,78,1562,71,2069,1470
12,충청북도,107,1809,74,1820,1347,106,2898,89,2759,...,162,3920,161,2397,3849,173,4454,173,2569,4440
13,충청남도,1823,50155,1803,2755,49673,2262,65446,2204,2890,...,1489,42873,1487,2873,42727,1286,36582,1280,2854,36520
14,전라북도,554,17161,552,3100,17112,595,17715,594,2978,...,612,16774,611,2747,16771,594,18510,593,3116,18488
15,전라남도,755,20900,746,2772,20679,753,21112,747,2805,...,761,22195,759,2915,22137,683,19047,667,2777,18530
16,경상북도,255,7002,253,2748,6952,270,7724,269,2865,...,352,14583,350,4154,14559,347,13916,344,4033,13885
17,경상남도,2015,67531,2014,3352,67509,2166,71440,2165,3299,...,2746,124754,2744,4544,124688,2252,62146,2250,2759,62068
18,제주도,86,1457,31,2480,769,83,1253,31,2024,...,25,519,16,2606,412,30,712,26,2575,660

In [65]:
df1 = df.copy()
df1

,시도별,2011,2011.1,2011.2,2011.3,2011.4,2012,2012.1,2012.2,2012.3,...,2019,2019.1,2019.2,2019.3,2019.4,2020,2020.1,2020.2,2020.3,2020.4
0,시도별,딸기:면적 (ha),생산량 (톤),시설딸기:면적 (ha),10a당 생산량 (kg),생산량 (톤),딸기:면적 (ha),생산량 (톤),시설딸기:면적 (ha),10a당 생산량 (kg),...,딸기:면적 (ha),생산량 (톤),시설딸기:면적 (ha),10a당 생산량 (kg),생산량 (톤),딸기:면적 (ha),생산량 (톤),시설딸기:면적 (ha),10a당 생산량 (kg),생산량 (톤)
1,계,5816,171519,5681,2979,169243,6435,192140,6290,3005,...,6462,234225,6421,3633,233291,5683,163646,5634,2885,162520
2,서울특별시,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,부산광역시,0,0,0,0,0,4,132,4,3299,...,0,5,0,0,0,1,42,1,2759,24
4,대구광역시,0,0,0,0,0,0,0,0,0,...,2,62,2,3403,62,0,0,0,0,0
5,인천광역시,11,254,0,0,0,9,105,0,0,...,24,601,19,2602,504,26,659,24,2601,617
6,광주광역시,47,1213,46,2583,1188,46,1256,46,2731,...,72,2662,72,3679,2660,64,2180,64,3392,2180
7,대전광역시,0,0,0,0,0,0,0,0,0,...,0,5,0,1404,2,0,0,0,0,0
8,울산광역시,0,0,0,0,0,0,0,0,0,...,18,410,17,2238,381,22,471,20,2074,415
9,세종특별자치시,-,-,-,-,-,-,-,-,-,...,20,463,20,2348,463,6,146,6,2439,146
10,경기도,109,2886,108,2651,2863,99,2141,99,2163,...,114,3017,109,2675,2905,122,3219,115,2669,3077
11,강원도,54,1151,54,2131,1151,42,918,42,2185,...,65,1382,54,2179,1171,78,1562,71,2069,1470
12,충청북도,107,1809,74,1820,1347,106,2898,89,2759,...,162,3920,161,2397,3849,173,4454,173,2569,4440
13,충청남도,1823,50155,1803,2755,49673,2262,65446,2204,2890,...,1489,42873,1487,2873,42727,1286,36582,1280,2854,36520
14,전라북도,554,17161,552,3100,17112,595,17715,594,2978,...,612,16774,611,2747,16771,594,18510,593,3116,18488
15,전라남도,755,20900,746,2772,20679,753,21112,747,2805,...,761,22195,759,2915,22137,683,19047,667,2777,18530
16,경상북도,255,7002,253,2748,6952,270,7724,269,2865,...,352,14583,350,4154,14559,347,13916,344,4033,13885
17,경상남도,2015,67531,2014,3352,67509,2166,71440,2165,3299,...,2746,124754,2744,4544,124688,2252,62146,2250,2759,62068
18,제주도,86,1457,31,2480,769,83,1253,31,2024,...,25,519,16,2606,412,30,712,26,2575,660

In [72]:
df[:1].columns

Index(['시도별', '2011', '2011.1', '2011.2', '2011.3', '2011.4', '2012', '2012.1',
       '2012.2', '2012.3', '2012.4', '2013', '2013.1', '2013.2', '2013.3',
       '2013.4', '2014', '2014.1', '2014.2', '2014.3', '2014.4', '2015',
       '2015.1', '2015.2', '2015.3', '2015.4', '2016', '2016.1', '2016.2',
       '2016.3', '2016.4', '2017', '2017.1', '2017.2', '2017.3', '2017.4',
       '2018', '2018.1', '2018.2', '2018.3', '2018.4', '2019', '2019.1',
       '2019.2', '2019.3', '2019.4', '2020', '2020.1', '2020.2', '2020.3',
       '2020.4'],
      dtype='object')